name = "led-matrix-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
SPREADSHEET_ID = "1laNmzAhUHJpkm-DTqzn0fsZxZNZ7S-Du2-_m7WFDYc8"
SHEET_NAME = "leads"

# Add these as secrets via:
# wrangler secret put GOOGLE_CREDENTIALS
# wrangler secret put TIKTOK_ACCESS_TOKEN
# wrangler secret put FB_ACCESS_TOKEN
